# Sample config file for integrating DCGM and prometheus
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration instructing prometheus to scrape the output of dcgm_prometheus.py, which in
# this example is running on host 'node01'
# To add this to an existing Prometheus config file, just add portion from job_name on to the existing
# scrape_configs
scrape_configs:
  - job_name: 'slurm'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      # hostname:port. dcgm_prometheus.py will publish to port 8000 by default. If you use -p to change this
      # when invoking the script, be sure to update it here
            - targets: ['INSTANCE_HOSTNAME:8090']
  - job_name: 'node'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      # hostname:port. dcgm_prometheus.py will publish to port 8000 by default. If you use -p to change this
      # when invoking the script, be sure to update it here
            - targets: ['INSTANCE_HOSTNAME:9100']
  

remote_write:
  - url: PROMETHEUS_URL
    sigv4:
      region: REGION
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500